AllCops:
  Exclude:
  - 'doc/**/*'
  - 'spec/**/*'
  - 'tmp/**/*'
  - 'Gemfile'
  - 'hcloud.gemspec'
  - 'Rakefile'
  - 'bin/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Layout/EndOfLine:
  EnforcedStyle: lf
